apiVersion: v1
kind: Pod
metadata:
  name: jb-s3-bucket-ls
spec:
  containers:
  - name: jb-s3-bucket-ls
    image: ACCOUNTID.dkr.ecr.us-west-2.amazonaws.com/s3bucketlist
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: s3-bucket-secret
  imagePullSecrets:
    - name: aws-ecr
    

